### ISSUE TITLE
Weapons specifically designed for killing animals do negligible damage to them.

### ISSUE THREAD

**Issue by Chatter42** [AEIOU-station/AEIOUStation13#134]
#### Brief description of the issue
The Ryder BB gun and phase carbine weapons do only the base damage of 3 and 5 to mobs with sa_animal intelligence when they are meant to do a total of 35 and 50 damage respectively.
#### What you expected to happen
For the phase carbine and BB gun to deal respectable damage to wildlife, or at least be able to kill something like a station pet with one or two shots.

#### What actually happened
Run in terror from spiders while trying to shoot at them with your explorer carbine only for the cells to completely empty and realize you didn't do significant damage with any individual shot. Shooting passive mobs yields similarly unimpressive results.

#### Steps to reproduce
- (Step 1) Spawn a weapon like the phase carbine that is meant to do bonus damage to animals.
- (Step 2) Shoot an animal with the weapon.
- (Step 3) Check its health variable and realize it only did 5 damage instead of the 50 it's meant to do.

#### Code Revision
Server revision: master - 2018-12-13
142bdd50ab91872967d65aedbeb91365a5687ea4

**Comment by EvilJackCarver** [comment]
Somewhere between the time I enabled it (#30) and the present, it got disabled again.

Easy fix, but I don't have the time. Gotta go to work.

https://github.com/AEIOU-station/AEIOUStation13/blob/master/code/modules/mob/living/simple_animal/simple_animal.dm#L606
