### ISSUE TITLE
Mapping inconsistency: Fore starbd. solars aren't wired up.

### ISSUE THREAD

**Issue by EvilJackCarver** [AEIOU-station/AEIOUStation13#169]
Fore starboard solars do not start wired up at roundstart, unlike the other three which do.

This is visible on the map, https://imgur.com/a/GL4Gstp

**Comment by YoteSanity** [comment]
This is resolved by #176.

**Comment by EvilJackCarver** [comment]
Resolved by #176 and I completely forgot to close it until now
