### ISSUE TITLE
Broken Sprites

### ISSUE THREAD

**Issue by EldritchClown** [AEIOU-station/AEIOUStation13#86]
#### Brief description of the issue
Several of the loadout and in-game sprites are broken.

#### List of known Broken Sprites
- Clutchbag
- Chaps
- Riding Crop
- Metal Necklace, I believe
- The Life Crystal box, whatever that is
- The Skrell Hairtacle Accessories
- Lesser concerns are the hardsuit sprites, but they're broken for humanoids like the Akula and the Tajara. Of course they're broken for Teshari, but I understand that that there's a lot of hard work, given having to make a new sprite altogether, but I think the other humanoids can at least deal with a squished muzzle and stuffing that thicc-ass tail down their pantlegs for a while until somebody feels like making a new sprite for them lol. Specifically, the asset protection sprite. Not sure yet if this is something that applies to ALL sprites regarding hardsuits/RIGs

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by lbnesquik** [comment]
Not sure about hardsuits but chaps are fine. Riding crops, necklace and metal necklaces are due to an issue with a virgo icon file.

**Comment by lbnesquik** [comment]
All skrell hair accessories work for me.
